Quest_3 : main_executable_module.o
	gcc main_executable_module.o -o Quest_3

main_executable_module.o : main_executable_module.c
	gcc -c main_executable_module.c -o main_executable_module.o


data_io.o : ../data_libs/data_io.c
	gcc -c ../data_libs/data_io.c -o data_io.o

data_stat.o : ../data_libs/data_stat.c
	gcc -c ../data_libs/data_stat.c -o data_stat.o

data_process.o : ../data_libs/data_process.c
	gcc -c ../data_libs/data_process.c -o data_process.o
